import { useState, useEffect, useCallback } from 'react'
import { ImportProfile, ImportSession, ImportRow, listImportProfiles, createImportProfile, uploadImport, previewImport, commitImport, listAccounts, Account } from '../api'
import { Alert } from '../components/ui/alert'
import { Button } from '../components/ui/button'
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '../components/ui/card'
import { Input } from '../components/ui/input'
import { Select } from '../components/ui/select'
import { Table, TBody, TD, TH, THead, TR } from '../components/ui/table'
import { Textarea } from '../components/ui/textarea'

export default function ImportPage() {
  const [profiles, setProfiles] = useState<ImportProfile[]>([]); const [accounts, setAccounts] = useState<Account[]>([])
  const [showProfileForm, setShowProfileForm] = useState(false); const [pName, setPName] = useState(''); const [pAccount, setPAccount] = useState(''); const [pSep, setPSep] = useState(','); const [pDateFmt, setPDateFmt] = useState('2006-01-02'); const [pMapping, setPMapping] = useState('{"date":0,"amount":1,"currency":2,"description":3}'); const [pFlip, setPFlip] = useState(false); const [pSkip, setPSkip] = useState(1)
  const [selectedProfile, setSelectedProfile] = useState(''); const [file, setFile] = useState<File | null>(null); const [session, setSession] = useState<ImportSession | null>(null); const [rows, setRows] = useState<ImportRow[]>([]); const [error, setError] = useState(''); const [loading, setLoading] = useState(false)
  const loadProfiles = useCallback(async () => { try { const [p, a] = await Promise.all([listImportProfiles(), listAccounts()]); setProfiles(p || []); setAccounts(a || []) } catch {} }, [])
  useEffect(() => { loadProfiles() }, [loadProfiles])
  const saveProfile = async () => { try { await createImportProfile({ name: pName, account_id: pAccount, separator: pSep, date_format: pDateFmt, column_mapping: JSON.parse(pMapping), amount_sign_flip: pFlip, skip_header_rows: pSkip }); setShowProfileForm(false); loadProfiles() } catch (e: unknown) { setError((e as Error).message) } }
  const doUpload = async () => { if (!file || !selectedProfile) return; setLoading(true); setError(''); try { const s = await uploadImport(selectedProfile, file); setSession(s); const p = await previewImport(s.ID); setSession(p.import); setRows(p.rows || []) } catch (e: unknown) { setError((e as Error).message) } finally { setLoading(false) } }
  const doCommit = async () => { if (!session) return; setLoading(true); setError(''); try { const r = await commitImport(session.ID); setSession(r); const p = await previewImport(r.ID); setRows(p.rows || []) } catch (e: unknown) { setError((e as Error).message) } finally { setLoading(false) } }
  const profileAccount = (id: string) => accounts.find(a => a.ID === id)?.Name || id.slice(0, 8)

  return <div className="space-y-4">{error && <Alert>{error}</Alert>}
    <Card><CardHeader className="flex flex-row items-center justify-between"><div><CardTitle className="text-base">Step 1 — Import profile</CardTitle><CardDescription>Set parsing rules once and reuse them</CardDescription></div><Button variant="outline" size="sm" onClick={() => setShowProfileForm(v => !v)}>{showProfileForm ? 'Close' : 'New profile'}</Button></CardHeader><CardContent className="space-y-3">{showProfileForm && <div className="grid gap-2 md:grid-cols-2"><Input value={pName} onChange={e => setPName(e.target.value)} placeholder="Profile name" /><Select value={pAccount} onChange={e => setPAccount(e.target.value)}><option value="">Account...</option>{accounts.map(a => <option key={a.ID} value={a.ID}>{a.Name}</option>)}</Select><Input value={pSep} onChange={e => setPSep(e.target.value)} placeholder="Separator" /><Input value={pDateFmt} onChange={e => setPDateFmt(e.target.value)} placeholder="Date format" /><Textarea className="md:col-span-2" value={pMapping} onChange={e => setPMapping(e.target.value)} /><label className="flex items-center gap-2 text-sm text-[var(--muted-foreground)]"><input type="checkbox" checked={pFlip} onChange={e => setPFlip(e.target.checked)} /> Flip amount sign</label><Input type="number" value={pSkip} onChange={e => setPSkip(parseInt(e.target.value) || 0)} /><div className="md:col-span-2"><Button onClick={saveProfile}>Save profile</Button></div></div>}
      <Table><TBody>{profiles.map(p => <TR key={p.ID}><TD>{p.Name}</TD><TD>{profileAccount(p.AccountID)}</TD><TD className="text-[var(--muted-foreground)]">sep: {p.Separator}</TD></TR>)}{profiles.length===0 && <TR><TD colSpan={3} className="text-center text-[var(--muted-foreground)]">No profiles yet</TD></TR>}</TBody></Table>
    </CardContent></Card>

    <Card><CardHeader><CardTitle className="text-base">Step 2 — Upload and preview</CardTitle></CardHeader><CardContent className="flex flex-wrap items-center gap-2"><Select value={selectedProfile} onChange={e => setSelectedProfile(e.target.value)} className="w-56"><option value="">Select profile...</option>{profiles.map(p => <option key={p.ID} value={p.ID}>{p.Name}</option>)}</Select><Input type="file" accept=".csv" onChange={e => setFile(e.target.files?.[0] || null)} className="max-w-xs" /><Button onClick={doUpload} disabled={!file || !selectedProfile || loading}>{loading ? 'Processing...' : 'Upload & preview'}</Button></CardContent></Card>

    {session && <Card><CardHeader className="flex flex-row items-center justify-between"><CardTitle className="text-base">Step 3 — Review and commit ({session.Status})</CardTitle>{session.Status === 'previewed' && <Button onClick={doCommit} disabled={loading}>{loading ? 'Committing...' : 'Commit import'}</Button>}</CardHeader><CardContent><p className="mb-2 text-sm text-[var(--muted-foreground)]">Total {session.TotalRows} · Imported {session.ImportedRows} · Skipped {session.SkippedRows} · Errors {session.ErrorRows}</p><div className="overflow-x-auto"><Table><THead><TR><TH>#</TH><TH>Status</TH><TH>Data</TH><TH>Error</TH></TR></THead><TBody>{rows.map(r => <TR key={r.ID} className={r.Status === 'error' ? 'bg-rose-50' : r.Status === 'skipped' ? 'bg-amber-50' : ''}><TD>{r.RowNumber}</TD><TD>{r.Status}</TD><TD className="max-w-sm truncate">{r.RawData}</TD><TD className="text-rose-600">{r.ErrorMessage}</TD></TR>)}</TBody></Table></div></CardContent></Card>}
  </div>
}
